<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IntelOrca.Biohazard.BioRand.RECV</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="BioRand.RECV.Tests" />
  </ItemGroup>
  <Target Name="SetInformationalVersion" BeforeTargets="CoreGenerateAssemblyInfo">
    <Exec Command="git rev-parse --short HEAD" ConsoleToMSBuild="true" WorkingDirectory="$(MSBuildProjectDirectory)/../..">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitCommitHash" />
    </Exec>
    <PropertyGroup>
      <InformationalVersion>$(GitCommitHash)</InformationalVersion>
    </PropertyGroup>
  </Target>
  <ItemGroup>
    <PackageReference Include="IntelOrca.Biohazard.BioRand.Common" Version="1.6.1" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="data\graph.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\lib\biohazard-utils\src\IntelOrca.Biohazard\IntelOrca.Biohazard.csproj" />
    <ProjectReference Include="..\..\lib\Ps2IsoTools\Ps2IsoTools\Ps2IsoTools.csproj" />
  </ItemGroup>
</Project>
